module.exports = [
  {
    Country: "Switzerland",
    "Cost of Living Index": 122.4,
    "Rent Index": 50.25,
    "Cost of Living Plus Rent Index": 87.89,
    "Groceries Index": 120.27,
    "Restaurant Price Index": 123.01,
    "Local Purchasing Power Index": 119.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Norway",
    "Cost of Living Index": 101.43,
    "Rent Index": 36.15,
    "Cost of Living Plus Rent Index": 70.21,
    "Groceries Index": 91.14,
    "Restaurant Price Index": 109.28,
    "Local Purchasing Power Index": 88.38,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iceland",
    "Cost of Living Index": 100.48,
    "Rent Index": 46.95,
    "Cost of Living Plus Rent Index": 74.88,
    "Groceries Index": 86.89,
    "Restaurant Price Index": 113.74,
    "Local Purchasing Power Index": 79.44,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Japan",
    "Cost of Living Index": 83.35,
    "Rent Index": 25.97,
    "Cost of Living Plus Rent Index": 55.9,
    "Groceries Index": 81.82,
    "Restaurant Price Index": 48.95,
    "Local Purchasing Power Index": 87.28,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Denmark",
    "Cost of Living Index": 83,
    "Rent Index": 31.92,
    "Cost of Living Plus Rent Index": 58.57,
    "Groceries Index": 61.74,
    "Restaurant Price Index": 100.75,
    "Local Purchasing Power Index": 100.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bahamas",
    "Cost of Living Index": 82.51,
    "Rent Index": 36.36,
    "Cost of Living Plus Rent Index": 60.43,
    "Groceries Index": 62.65,
    "Restaurant Price Index": 83.66,
    "Local Purchasing Power Index": 54.18,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Luxembourg",
    "Cost of Living Index": 81.89,
    "Rent Index": 54.92,
    "Cost of Living Plus Rent Index": 68.99,
    "Groceries Index": 69.1,
    "Restaurant Price Index": 89.85,
    "Local Purchasing Power Index": 103.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Israel",
    "Cost of Living Index": 81.15,
    "Rent Index": 31.33,
    "Cost of Living Plus Rent Index": 57.32,
    "Groceries Index": 66.31,
    "Restaurant Price Index": 88.65,
    "Local Purchasing Power Index": 78.09,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Singapore",
    "Cost of Living Index": 81.1,
    "Rent Index": 63.27,
    "Cost of Living Plus Rent Index": 72.58,
    "Groceries Index": 66.75,
    "Restaurant Price Index": 58.99,
    "Local Purchasing Power Index": 88.96,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "South Korea",
    "Cost of Living Index": 78.18,
    "Rent Index": 22.86,
    "Cost of Living Plus Rent Index": 51.72,
    "Groceries Index": 91.31,
    "Restaurant Price Index": 44.87,
    "Local Purchasing Power Index": 85.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Hong Kong",
    "Cost of Living Index": 77.22,
    "Rent Index": 79.57,
    "Cost of Living Plus Rent Index": 78.35,
    "Groceries Index": 75.94,
    "Restaurant Price Index": 54.36,
    "Local Purchasing Power Index": 65.32,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Barbados",
    "Cost of Living Index": 76.02,
    "Rent Index": 19.7,
    "Cost of Living Plus Rent Index": 49.08,
    "Groceries Index": 65.2,
    "Restaurant Price Index": 68.14,
    "Local Purchasing Power Index": 51.1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ireland",
    "Cost of Living Index": 75.91,
    "Rent Index": 43.88,
    "Cost of Living Plus Rent Index": 60.59,
    "Groceries Index": 58.35,
    "Restaurant Price Index": 81.24,
    "Local Purchasing Power Index": 80.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "France",
    "Cost of Living Index": 74.14,
    "Rent Index": 25.39,
    "Cost of Living Plus Rent Index": 50.82,
    "Groceries Index": 67.9,
    "Restaurant Price Index": 72.54,
    "Local Purchasing Power Index": 80.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Netherlands",
    "Cost of Living Index": 73.75,
    "Rent Index": 35.18,
    "Cost of Living Plus Rent Index": 55.3,
    "Groceries Index": 55.87,
    "Restaurant Price Index": 80.48,
    "Local Purchasing Power Index": 90.73,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Australia",
    "Cost of Living Index": 73.54,
    "Rent Index": 34.86,
    "Cost of Living Plus Rent Index": 55.04,
    "Groceries Index": 67.23,
    "Restaurant Price Index": 70.32,
    "Local Purchasing Power Index": 107.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "New Zealand",
    "Cost of Living Index": 72.53,
    "Rent Index": 32.09,
    "Cost of Living Plus Rent Index": 53.19,
    "Groceries Index": 64.69,
    "Restaurant Price Index": 68.8,
    "Local Purchasing Power Index": 92.66,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Belgium",
    "Cost of Living Index": 71.78,
    "Rent Index": 25.43,
    "Cost of Living Plus Rent Index": 49.61,
    "Groceries Index": 58.66,
    "Restaurant Price Index": 80.14,
    "Local Purchasing Power Index": 86.28,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Seychelles",
    "Cost of Living Index": 71.59,
    "Rent Index": 32.34,
    "Cost of Living Plus Rent Index": 52.81,
    "Groceries Index": 64.61,
    "Restaurant Price Index": 84.86,
    "Local Purchasing Power Index": 21.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United States",
    "Cost of Living Index": 71.05,
    "Rent Index": 40.32,
    "Cost of Living Plus Rent Index": 56.36,
    "Groceries Index": 66.61,
    "Restaurant Price Index": 70.74,
    "Local Purchasing Power Index": 109.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Austria",
    "Cost of Living Index": 70.38,
    "Rent Index": 26.81,
    "Cost of Living Plus Rent Index": 49.54,
    "Groceries Index": 61.73,
    "Restaurant Price Index": 68.09,
    "Local Purchasing Power Index": 82.38,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Finland",
    "Cost of Living Index": 70.29,
    "Rent Index": 26.16,
    "Cost of Living Plus Rent Index": 49.18,
    "Groceries Index": 56.52,
    "Restaurant Price Index": 76.81,
    "Local Purchasing Power Index": 99.93,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Sweden",
    "Cost of Living Index": 69.85,
    "Rent Index": 25.9,
    "Cost of Living Plus Rent Index": 48.83,
    "Groceries Index": 60.47,
    "Restaurant Price Index": 72.35,
    "Local Purchasing Power Index": 101.73,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Canada",
    "Cost of Living Index": 67.62,
    "Rent Index": 30.73,
    "Cost of Living Plus Rent Index": 49.98,
    "Groceries Index": 63.68,
    "Restaurant Price Index": 63.53,
    "Local Purchasing Power Index": 95.09,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Puerto Rico",
    "Cost of Living Index": 67.54,
    "Rent Index": 19.29,
    "Cost of Living Plus Rent Index": 44.46,
    "Groceries Index": 65.76,
    "Restaurant Price Index": 58.68,
    "Local Purchasing Power Index": 79.38,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Malta",
    "Cost of Living Index": 67.46,
    "Rent Index": 31.04,
    "Cost of Living Plus Rent Index": 50.04,
    "Groceries Index": 54.9,
    "Restaurant Price Index": 75.94,
    "Local Purchasing Power Index": 46.32,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United Kingdom",
    "Cost of Living Index": 67.28,
    "Rent Index": 29.85,
    "Cost of Living Plus Rent Index": 49.38,
    "Groceries Index": 51.27,
    "Restaurant Price Index": 74.13,
    "Local Purchasing Power Index": 91.73,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Italy",
    "Cost of Living Index": 67.26,
    "Rent Index": 21.22,
    "Cost of Living Plus Rent Index": 45.24,
    "Groceries Index": 55.44,
    "Restaurant Price Index": 72.32,
    "Local Purchasing Power Index": 65.59,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Germany",
    "Cost of Living Index": 65.26,
    "Rent Index": 27.06,
    "Cost of Living Plus Rent Index": 46.99,
    "Groceries Index": 49.23,
    "Restaurant Price Index": 61.58,
    "Local Purchasing Power Index": 102.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Macao",
    "Cost of Living Index": 64.84,
    "Rent Index": 43.98,
    "Cost of Living Plus Rent Index": 54.87,
    "Groceries Index": 62,
    "Restaurant Price Index": 43.37,
    "Local Purchasing Power Index": 80.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Qatar",
    "Cost of Living Index": 64.04,
    "Rent Index": 47.44,
    "Cost of Living Plus Rent Index": 56.1,
    "Groceries Index": 53.61,
    "Restaurant Price Index": 66.83,
    "Local Purchasing Power Index": 111.69,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United Arab Emirates",
    "Cost of Living Index": 61.98,
    "Rent Index": 41.07,
    "Cost of Living Plus Rent Index": 51.98,
    "Groceries Index": 47.63,
    "Restaurant Price Index": 61.32,
    "Local Purchasing Power Index": 91.58,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Taiwan",
    "Cost of Living Index": 61.37,
    "Rent Index": 16.42,
    "Cost of Living Plus Rent Index": 39.87,
    "Groceries Index": 71.51,
    "Restaurant Price Index": 28.49,
    "Local Purchasing Power Index": 65.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Lebanon",
    "Cost of Living Index": 60.5,
    "Rent Index": 24.54,
    "Cost of Living Plus Rent Index": 43.3,
    "Groceries Index": 43.92,
    "Restaurant Price Index": 58.16,
    "Local Purchasing Power Index": 44.47,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bahrain",
    "Cost of Living Index": 58.94,
    "Rent Index": 30.95,
    "Cost of Living Plus Rent Index": 45.55,
    "Groceries Index": 48.11,
    "Restaurant Price Index": 54.55,
    "Local Purchasing Power Index": 57.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Cyprus",
    "Cost of Living Index": 57.93,
    "Rent Index": 20.54,
    "Cost of Living Plus Rent Index": 40.05,
    "Groceries Index": 44.21,
    "Restaurant Price Index": 63.11,
    "Local Purchasing Power Index": 57.41,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Jamaica",
    "Cost of Living Index": 57.82,
    "Rent Index": 15.25,
    "Cost of Living Plus Rent Index": 37.46,
    "Groceries Index": 58.96,
    "Restaurant Price Index": 38.12,
    "Local Purchasing Power Index": 32.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Greece",
    "Cost of Living Index": 55.67,
    "Rent Index": 11.68,
    "Cost of Living Plus Rent Index": 34.62,
    "Groceries Index": 41.63,
    "Restaurant Price Index": 53.74,
    "Local Purchasing Power Index": 43.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Zimbabwe",
    "Cost of Living Index": 55.3,
    "Rent Index": 11.02,
    "Cost of Living Plus Rent Index": 34.12,
    "Groceries Index": 50.8,
    "Restaurant Price Index": 40.79,
    "Local Purchasing Power Index": 26.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Palestine",
    "Cost of Living Index": 54.54,
    "Rent Index": 8.83,
    "Cost of Living Plus Rent Index": 32.68,
    "Groceries Index": 46.67,
    "Restaurant Price Index": 38.93,
    "Local Purchasing Power Index": 46.91,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ethiopia",
    "Cost of Living Index": 54.39,
    "Rent Index": 20.9,
    "Cost of Living Plus Rent Index": 38.37,
    "Groceries Index": 36.3,
    "Restaurant Price Index": 19.37,
    "Local Purchasing Power Index": 8.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Panama",
    "Cost of Living Index": 54.16,
    "Rent Index": 24.76,
    "Cost of Living Plus Rent Index": 40.09,
    "Groceries Index": 53.03,
    "Restaurant Price Index": 47.27,
    "Local Purchasing Power Index": 34.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Costa Rica",
    "Cost of Living Index": 53.98,
    "Rent Index": 15.55,
    "Cost of Living Plus Rent Index": 35.6,
    "Groceries Index": 49.6,
    "Restaurant Price Index": 43.51,
    "Local Purchasing Power Index": 42.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Spain",
    "Cost of Living Index": 53.77,
    "Rent Index": 21.77,
    "Cost of Living Plus Rent Index": 38.46,
    "Groceries Index": 42.38,
    "Restaurant Price Index": 52.07,
    "Local Purchasing Power Index": 72.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Trinidad And Tobago",
    "Cost of Living Index": 53.7,
    "Rent Index": 17.26,
    "Cost of Living Plus Rent Index": 36.27,
    "Groceries Index": 49.43,
    "Restaurant Price Index": 49.83,
    "Local Purchasing Power Index": 45.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Jordan",
    "Cost of Living Index": 53.67,
    "Rent Index": 11.54,
    "Cost of Living Plus Rent Index": 33.52,
    "Groceries Index": 43.32,
    "Restaurant Price Index": 47.12,
    "Local Purchasing Power Index": 34.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Slovenia",
    "Cost of Living Index": 53.43,
    "Rent Index": 17.09,
    "Cost of Living Plus Rent Index": 36.05,
    "Groceries Index": 43.76,
    "Restaurant Price Index": 45.43,
    "Local Purchasing Power Index": 66.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Mauritius",
    "Cost of Living Index": 53.04,
    "Rent Index": 11.99,
    "Cost of Living Plus Rent Index": 33.41,
    "Groceries Index": 48.94,
    "Restaurant Price Index": 43.96,
    "Local Purchasing Power Index": 30.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Uruguay",
    "Cost of Living Index": 51.04,
    "Rent Index": 14.43,
    "Cost of Living Plus Rent Index": 33.53,
    "Groceries Index": 40.12,
    "Restaurant Price Index": 47.41,
    "Local Purchasing Power Index": 37.46,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Estonia",
    "Cost of Living Index": 50.93,
    "Rent Index": 15.41,
    "Cost of Living Plus Rent Index": 33.94,
    "Groceries Index": 36.57,
    "Restaurant Price Index": 52.94,
    "Local Purchasing Power Index": 71.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kuwait",
    "Cost of Living Index": 50.37,
    "Rent Index": 31.21,
    "Cost of Living Plus Rent Index": 41.21,
    "Groceries Index": 34.68,
    "Restaurant Price Index": 47.08,
    "Local Purchasing Power Index": 85.59,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Thailand",
    "Cost of Living Index": 49.77,
    "Rent Index": 17.1,
    "Cost of Living Plus Rent Index": 34.14,
    "Groceries Index": 49.2,
    "Restaurant Price Index": 24.9,
    "Local Purchasing Power Index": 35.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Croatia",
    "Cost of Living Index": 49.7,
    "Rent Index": 13.5,
    "Cost of Living Plus Rent Index": 32.38,
    "Groceries Index": 39.9,
    "Restaurant Price Index": 42.44,
    "Local Purchasing Power Index": 50.42,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Portugal",
    "Cost of Living Index": 49.52,
    "Rent Index": 21.81,
    "Cost of Living Plus Rent Index": 36.27,
    "Groceries Index": 38.14,
    "Restaurant Price Index": 42.48,
    "Local Purchasing Power Index": 49.43,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Oman",
    "Cost of Living Index": 49.28,
    "Rent Index": 17.98,
    "Cost of Living Plus Rent Index": 34.31,
    "Groceries Index": 43.5,
    "Restaurant Price Index": 44.26,
    "Local Purchasing Power Index": 80.97,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Belize",
    "Cost of Living Index": 49.23,
    "Rent Index": 9.74,
    "Cost of Living Plus Rent Index": 30.34,
    "Groceries Index": 41.89,
    "Restaurant Price Index": 37.05,
    "Local Purchasing Power Index": 57.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Saudi Arabia",
    "Cost of Living Index": 48.34,
    "Rent Index": 11.39,
    "Cost of Living Plus Rent Index": 30.67,
    "Groceries Index": 37.89,
    "Restaurant Price Index": 33.51,
    "Local Purchasing Power Index": 100,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Latvia",
    "Cost of Living Index": 47.94,
    "Rent Index": 12.34,
    "Cost of Living Plus Rent Index": 30.91,
    "Groceries Index": 34.85,
    "Restaurant Price Index": 42.88,
    "Local Purchasing Power Index": 52.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Cambodia",
    "Cost of Living Index": 47.49,
    "Rent Index": 14.9,
    "Cost of Living Plus Rent Index": 31.9,
    "Groceries Index": 44.56,
    "Restaurant Price Index": 25.19,
    "Local Purchasing Power Index": 11.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Fiji",
    "Cost of Living Index": 47.48,
    "Rent Index": 18.55,
    "Cost of Living Plus Rent Index": 33.64,
    "Groceries Index": 52.67,
    "Restaurant Price Index": 35.87,
    "Local Purchasing Power Index": 33.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Czech Republic",
    "Cost of Living Index": 46.15,
    "Rent Index": 19.56,
    "Cost of Living Plus Rent Index": 33.43,
    "Groceries Index": 38.13,
    "Restaurant Price Index": 34.1,
    "Local Purchasing Power Index": 62.82,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "El Salvador",
    "Cost of Living Index": 45.57,
    "Rent Index": 13.48,
    "Cost of Living Plus Rent Index": 30.22,
    "Groceries Index": 43.67,
    "Restaurant Price Index": 34.8,
    "Local Purchasing Power Index": 24.71,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Brunei",
    "Cost of Living Index": 44.71,
    "Rent Index": 23.08,
    "Cost of Living Plus Rent Index": 34.36,
    "Groceries Index": 37.11,
    "Restaurant Price Index": 38.06,
    "Local Purchasing Power Index": 86.95,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Nicaragua",
    "Cost of Living Index": 44.56,
    "Rent Index": 7.61,
    "Cost of Living Plus Rent Index": 26.88,
    "Groceries Index": 41.71,
    "Restaurant Price Index": 31.41,
    "Local Purchasing Power Index": 23.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Slovakia",
    "Cost of Living Index": 44.46,
    "Rent Index": 16.11,
    "Cost of Living Plus Rent Index": 30.9,
    "Groceries Index": 37.51,
    "Restaurant Price Index": 33.82,
    "Local Purchasing Power Index": 56.94,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Lithuania",
    "Cost of Living Index": 44.28,
    "Rent Index": 13.65,
    "Cost of Living Plus Rent Index": 29.63,
    "Groceries Index": 33.63,
    "Restaurant Price Index": 42.7,
    "Local Purchasing Power Index": 57.85,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Dominican Republic",
    "Cost of Living Index": 44.06,
    "Rent Index": 10.62,
    "Cost of Living Plus Rent Index": 28.06,
    "Groceries Index": 35.93,
    "Restaurant Price Index": 38.27,
    "Local Purchasing Power Index": 23.95,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Chile",
    "Cost of Living Index": 43.62,
    "Rent Index": 13.39,
    "Cost of Living Plus Rent Index": 29.16,
    "Groceries Index": 36.45,
    "Restaurant Price Index": 41.57,
    "Local Purchasing Power Index": 42.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Cuba",
    "Cost of Living Index": 43.46,
    "Rent Index": 4.84,
    "Cost of Living Plus Rent Index": 24.99,
    "Groceries Index": 37.4,
    "Restaurant Price Index": 30.95,
    "Local Purchasing Power Index": 2.18,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Suriname",
    "Cost of Living Index": 43.14,
    "Rent Index": 7.79,
    "Cost of Living Plus Rent Index": 26.23,
    "Groceries Index": 45.78,
    "Restaurant Price Index": 34.98,
    "Local Purchasing Power Index": 22.39,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Namibia",
    "Cost of Living Index": 43.1,
    "Rent Index": 16.12,
    "Cost of Living Plus Rent Index": 30.19,
    "Groceries Index": 36.8,
    "Restaurant Price Index": 39.22,
    "Local Purchasing Power Index": 55.65,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "South Africa",
    "Cost of Living Index": 42.87,
    "Rent Index": 16.61,
    "Cost of Living Plus Rent Index": 30.31,
    "Groceries Index": 33.29,
    "Restaurant Price Index": 40.58,
    "Local Purchasing Power Index": 73.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Guatemala",
    "Cost of Living Index": 42.7,
    "Rent Index": 15.29,
    "Cost of Living Plus Rent Index": 29.59,
    "Groceries Index": 37.41,
    "Restaurant Price Index": 33,
    "Local Purchasing Power Index": 39.83,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Honduras",
    "Cost of Living Index": 42.17,
    "Rent Index": 10.6,
    "Cost of Living Plus Rent Index": 27.07,
    "Groceries Index": 33.33,
    "Restaurant Price Index": 30.55,
    "Local Purchasing Power Index": 30.26,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Myanmar",
    "Cost of Living Index": 42.11,
    "Rent Index": 23.78,
    "Cost of Living Plus Rent Index": 33.35,
    "Groceries Index": 44.68,
    "Restaurant Price Index": 19.04,
    "Local Purchasing Power Index": 10.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ecuador",
    "Cost of Living Index": 40.98,
    "Rent Index": 11.96,
    "Cost of Living Plus Rent Index": 27.1,
    "Groceries Index": 35.46,
    "Restaurant Price Index": 30.66,
    "Local Purchasing Power Index": 36.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Hungary",
    "Cost of Living Index": 40.85,
    "Rent Index": 13.97,
    "Cost of Living Plus Rent Index": 27.99,
    "Groceries Index": 30.77,
    "Restaurant Price Index": 34.46,
    "Local Purchasing Power Index": 47.55,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Brazil",
    "Cost of Living Index": 40.22,
    "Rent Index": 10.65,
    "Cost of Living Plus Rent Index": 26.08,
    "Groceries Index": 29.2,
    "Restaurant Price Index": 30.78,
    "Local Purchasing Power Index": 32.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kenya",
    "Cost of Living Index": 40.21,
    "Rent Index": 10.73,
    "Cost of Living Plus Rent Index": 26.11,
    "Groceries Index": 35.35,
    "Restaurant Price Index": 35.06,
    "Local Purchasing Power Index": 27.32,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "China",
    "Cost of Living Index": 40.04,
    "Rent Index": 16.38,
    "Cost of Living Plus Rent Index": 28.72,
    "Groceries Index": 40.37,
    "Restaurant Price Index": 29.16,
    "Local Purchasing Power Index": 60.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Poland",
    "Cost of Living Index": 40.04,
    "Rent Index": 15.67,
    "Cost of Living Plus Rent Index": 28.38,
    "Groceries Index": 30.55,
    "Restaurant Price Index": 33.45,
    "Local Purchasing Power Index": 59.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Russia",
    "Cost of Living Index": 39.21,
    "Rent Index": 11.36,
    "Cost of Living Plus Rent Index": 25.89,
    "Groceries Index": 31.08,
    "Restaurant Price Index": 39.61,
    "Local Purchasing Power Index": 38.94,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Botswana",
    "Cost of Living Index": 39.13,
    "Rent Index": 11.12,
    "Cost of Living Plus Rent Index": 25.73,
    "Groceries Index": 31.74,
    "Restaurant Price Index": 39.98,
    "Local Purchasing Power Index": 58.1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Malaysia",
    "Cost of Living Index": 39.12,
    "Rent Index": 11,
    "Cost of Living Plus Rent Index": 25.67,
    "Groceries Index": 37.58,
    "Restaurant Price Index": 22.94,
    "Local Purchasing Power Index": 64.49,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iraq",
    "Cost of Living Index": 39.04,
    "Rent Index": 11.28,
    "Cost of Living Plus Rent Index": 25.76,
    "Groceries Index": 31.85,
    "Restaurant Price Index": 32.72,
    "Local Purchasing Power Index": 42.43,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iran",
    "Cost of Living Index": 39.01,
    "Rent Index": 14.48,
    "Cost of Living Plus Rent Index": 27.28,
    "Groceries Index": 35.54,
    "Restaurant Price Index": 25.12,
    "Local Purchasing Power Index": 22.69,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Somalia",
    "Cost of Living Index": 38.68,
    "Rent Index": 4.75,
    "Cost of Living Plus Rent Index": 22.45,
    "Groceries Index": 45.88,
    "Restaurant Price Index": 27.04,
    "Local Purchasing Power Index": 33.24,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Peru",
    "Cost of Living Index": 38.65,
    "Rent Index": 12.78,
    "Cost of Living Plus Rent Index": 26.28,
    "Groceries Index": 33.8,
    "Restaurant Price Index": 24.69,
    "Local Purchasing Power Index": 33.95,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Vietnam",
    "Cost of Living Index": 38.34,
    "Rent Index": 13.57,
    "Cost of Living Plus Rent Index": 26.5,
    "Groceries Index": 37.06,
    "Restaurant Price Index": 19.59,
    "Local Purchasing Power Index": 28.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Montenegro",
    "Cost of Living Index": 38.23,
    "Rent Index": 10.38,
    "Cost of Living Plus Rent Index": 24.91,
    "Groceries Index": 28.63,
    "Restaurant Price Index": 33.16,
    "Local Purchasing Power Index": 39.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ghana",
    "Cost of Living Index": 37.65,
    "Rent Index": 19.41,
    "Cost of Living Plus Rent Index": 28.93,
    "Groceries Index": 37.17,
    "Restaurant Price Index": 26.59,
    "Local Purchasing Power Index": 14.66,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Philippines",
    "Cost of Living Index": 37.63,
    "Rent Index": 9,
    "Cost of Living Plus Rent Index": 23.94,
    "Groceries Index": 33.46,
    "Restaurant Price Index": 20.84,
    "Local Purchasing Power Index": 23.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Indonesia",
    "Cost of Living Index": 37.27,
    "Rent Index": 10.62,
    "Cost of Living Plus Rent Index": 24.52,
    "Groceries Index": 37.36,
    "Restaurant Price Index": 18.25,
    "Local Purchasing Power Index": 25.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bulgaria",
    "Cost of Living Index": 36.7,
    "Rent Index": 9.64,
    "Cost of Living Plus Rent Index": 23.75,
    "Groceries Index": 30.09,
    "Restaurant Price Index": 29.14,
    "Local Purchasing Power Index": 49.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Albania",
    "Cost of Living Index": 36.39,
    "Rent Index": 8.55,
    "Cost of Living Plus Rent Index": 23.07,
    "Groceries Index": 28.39,
    "Restaurant Price Index": 26.75,
    "Local Purchasing Power Index": 29.56,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bosnia And Herzegovina",
    "Cost of Living Index": 35.97,
    "Rent Index": 6.72,
    "Cost of Living Plus Rent Index": 21.97,
    "Groceries Index": 28.08,
    "Restaurant Price Index": 25.1,
    "Local Purchasing Power Index": 41.83,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Mexico",
    "Cost of Living Index": 35.72,
    "Rent Index": 11.46,
    "Cost of Living Plus Rent Index": 24.11,
    "Groceries Index": 32.39,
    "Restaurant Price Index": 32.12,
    "Local Purchasing Power Index": 41.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Serbia",
    "Cost of Living Index": 35.72,
    "Rent Index": 9.08,
    "Cost of Living Plus Rent Index": 22.98,
    "Groceries Index": 25.46,
    "Restaurant Price Index": 28.63,
    "Local Purchasing Power Index": 36.72,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Romania",
    "Cost of Living Index": 35.31,
    "Rent Index": 10.05,
    "Cost of Living Plus Rent Index": 23.22,
    "Groceries Index": 29.03,
    "Restaurant Price Index": 30.5,
    "Local Purchasing Power Index": 48.86,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Tanzania",
    "Cost of Living Index": 35.25,
    "Rent Index": 14.04,
    "Cost of Living Plus Rent Index": 25.11,
    "Groceries Index": 29.66,
    "Restaurant Price Index": 22.57,
    "Local Purchasing Power Index": 17.58,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Belarus",
    "Cost of Living Index": 34.7,
    "Rent Index": 10.5,
    "Cost of Living Plus Rent Index": 23.13,
    "Groceries Index": 28.06,
    "Restaurant Price Index": 38.94,
    "Local Purchasing Power Index": 37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Turkey",
    "Cost of Living Index": 34.69,
    "Rent Index": 6.78,
    "Cost of Living Plus Rent Index": 21.34,
    "Groceries Index": 29.76,
    "Restaurant Price Index": 24.16,
    "Local Purchasing Power Index": 40.85,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bolivia",
    "Cost of Living Index": 34.56,
    "Rent Index": 10.93,
    "Cost of Living Plus Rent Index": 23.26,
    "Groceries Index": 28.09,
    "Restaurant Price Index": 25.11,
    "Local Purchasing Power Index": 39.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Morocco",
    "Cost of Living Index": 34.32,
    "Rent Index": 8.94,
    "Cost of Living Plus Rent Index": 22.18,
    "Groceries Index": 30.11,
    "Restaurant Price Index": 24.5,
    "Local Purchasing Power Index": 35.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Moldova",
    "Cost of Living Index": 33.7,
    "Rent Index": 8.4,
    "Cost of Living Plus Rent Index": 21.6,
    "Groceries Index": 25.96,
    "Restaurant Price Index": 27.79,
    "Local Purchasing Power Index": 27.57,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Rwanda",
    "Cost of Living Index": 33.35,
    "Rent Index": 11.88,
    "Cost of Living Plus Rent Index": 23.08,
    "Groceries Index": 26.83,
    "Restaurant Price Index": 29.17,
    "Local Purchasing Power Index": 19.32,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ukraine",
    "Cost of Living Index": 33.18,
    "Rent Index": 10.46,
    "Cost of Living Plus Rent Index": 22.31,
    "Groceries Index": 26.01,
    "Restaurant Price Index": 26.42,
    "Local Purchasing Power Index": 31.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Argentina",
    "Cost of Living Index": 32.95,
    "Rent Index": 8.33,
    "Cost of Living Plus Rent Index": 21.17,
    "Groceries Index": 25.82,
    "Restaurant Price Index": 30.52,
    "Local Purchasing Power Index": 47.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Armenia",
    "Cost of Living Index": 32.84,
    "Rent Index": 10.91,
    "Cost of Living Plus Rent Index": 22.35,
    "Groceries Index": 25.61,
    "Restaurant Price Index": 30.43,
    "Local Purchasing Power Index": 28,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bangladesh",
    "Cost of Living Index": 32.25,
    "Rent Index": 5.01,
    "Cost of Living Plus Rent Index": 19.22,
    "Groceries Index": 29.72,
    "Restaurant Price Index": 19.21,
    "Local Purchasing Power Index": 33.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Zambia",
    "Cost of Living Index": 31.72,
    "Rent Index": 7.39,
    "Cost of Living Plus Rent Index": 20.08,
    "Groceries Index": 26.86,
    "Restaurant Price Index": 22.07,
    "Local Purchasing Power Index": 54.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Sri Lanka",
    "Cost of Living Index": 31.61,
    "Rent Index": 7.74,
    "Cost of Living Plus Rent Index": 20.2,
    "Groceries Index": 35.09,
    "Restaurant Price Index": 18.76,
    "Local Purchasing Power Index": 24.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "North Macedonia",
    "Cost of Living Index": 31.59,
    "Rent Index": 6.49,
    "Cost of Living Plus Rent Index": 19.58,
    "Groceries Index": 24.94,
    "Restaurant Price Index": 23.31,
    "Local Purchasing Power Index": 37.15,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Paraguay",
    "Cost of Living Index": 31.1,
    "Rent Index": 9.66,
    "Cost of Living Plus Rent Index": 20.85,
    "Groceries Index": 25.03,
    "Restaurant Price Index": 25.01,
    "Local Purchasing Power Index": 32.6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Nigeria",
    "Cost of Living Index": 31,
    "Rent Index": 23.59,
    "Cost of Living Plus Rent Index": 27.45,
    "Groceries Index": 31.15,
    "Restaurant Price Index": 17.71,
    "Local Purchasing Power Index": 13.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Colombia",
    "Cost of Living Index": 30.66,
    "Rent Index": 9.58,
    "Cost of Living Plus Rent Index": 20.58,
    "Groceries Index": 25.05,
    "Restaurant Price Index": 22.44,
    "Local Purchasing Power Index": 31.12,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kazakhstan",
    "Cost of Living Index": 30.64,
    "Rent Index": 9.78,
    "Cost of Living Plus Rent Index": 20.66,
    "Groceries Index": 24.31,
    "Restaurant Price Index": 29.87,
    "Local Purchasing Power Index": 38.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Uganda",
    "Cost of Living Index": 30.18,
    "Rent Index": 10.15,
    "Cost of Living Plus Rent Index": 20.6,
    "Groceries Index": 25.25,
    "Restaurant Price Index": 22.14,
    "Local Purchasing Power Index": 20.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Algeria",
    "Cost of Living Index": 30.1,
    "Rent Index": 5.34,
    "Cost of Living Plus Rent Index": 18.26,
    "Groceries Index": 30.71,
    "Restaurant Price Index": 15.89,
    "Local Purchasing Power Index": 28.69,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Azerbaijan",
    "Cost of Living Index": 29.92,
    "Rent Index": 9.48,
    "Cost of Living Plus Rent Index": 20.15,
    "Groceries Index": 23.74,
    "Restaurant Price Index": 30.36,
    "Local Purchasing Power Index": 30.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Egypt",
    "Cost of Living Index": 29.54,
    "Rent Index": 5.49,
    "Cost of Living Plus Rent Index": 18.04,
    "Groceries Index": 25.5,
    "Restaurant Price Index": 23.53,
    "Local Purchasing Power Index": 22.41,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Nepal",
    "Cost of Living Index": 29.05,
    "Rent Index": 4.77,
    "Cost of Living Plus Rent Index": 17.44,
    "Groceries Index": 24.91,
    "Restaurant Price Index": 20.36,
    "Local Purchasing Power Index": 21.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Georgia",
    "Cost of Living Index": 28.48,
    "Rent Index": 9.8,
    "Cost of Living Plus Rent Index": 19.54,
    "Groceries Index": 23.05,
    "Restaurant Price Index": 26.66,
    "Local Purchasing Power Index": 24.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kosovo (Disputed Territory)",
    "Cost of Living Index": 28.47,
    "Rent Index": 8.47,
    "Cost of Living Plus Rent Index": 18.91,
    "Groceries Index": 26.53,
    "Restaurant Price Index": 21.04,
    "Local Purchasing Power Index": 48.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Venezuela",
    "Cost of Living Index": 27.17,
    "Rent Index": 6.81,
    "Cost of Living Plus Rent Index": 17.43,
    "Groceries Index": 28.29,
    "Restaurant Price Index": 24.41,
    "Local Purchasing Power Index": 2.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Tunisia",
    "Cost of Living Index": 27.04,
    "Rent Index": 5.51,
    "Cost of Living Plus Rent Index": 16.74,
    "Groceries Index": 25.25,
    "Restaurant Price Index": 14.95,
    "Local Purchasing Power Index": 34.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kyrgyzstan",
    "Cost of Living Index": 26.97,
    "Rent Index": 9.18,
    "Cost of Living Plus Rent Index": 18.46,
    "Groceries Index": 23.39,
    "Restaurant Price Index": 21.45,
    "Local Purchasing Power Index": 24.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Uzbekistan",
    "Cost of Living Index": 26.01,
    "Rent Index": 7.54,
    "Cost of Living Plus Rent Index": 17.18,
    "Groceries Index": 21.59,
    "Restaurant Price Index": 20.17,
    "Local Purchasing Power Index": 24.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Syria",
    "Cost of Living Index": 25.31,
    "Rent Index": 5.68,
    "Cost of Living Plus Rent Index": 15.92,
    "Groceries Index": 22.42,
    "Restaurant Price Index": 21.38,
    "Local Purchasing Power Index": 11.46,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "India",
    "Cost of Living Index": 24.58,
    "Rent Index": 5.68,
    "Cost of Living Plus Rent Index": 15.54,
    "Groceries Index": 24.55,
    "Restaurant Price Index": 17.17,
    "Local Purchasing Power Index": 54.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Afghanistan",
    "Cost of Living Index": 24.24,
    "Rent Index": 4.03,
    "Cost of Living Plus Rent Index": 14.58,
    "Groceries Index": 17.7,
    "Restaurant Price Index": 17.38,
    "Local Purchasing Power Index": 28.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Pakistan",
    "Cost of Living Index": 21.98,
    "Rent Index": 4.59,
    "Cost of Living Plus Rent Index": 13.66,
    "Groceries Index": 19.08,
    "Restaurant Price Index": 16.78,
    "Local Purchasing Power Index": 30.57,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
