module.exports = [
  {
    Country: "Venezuela",
    "Crime Index": 84.49,
    "Safety Index": 15.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Papua New Guinea",
    "Crime Index": 81.93,
    "Safety Index": 18.07,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "South Africa",
    "Crime Index": 77.49,
    "Safety Index": 22.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Afghanistan",
    "Crime Index": 76.23,
    "Safety Index": 23.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Honduras",
    "Crime Index": 76.11,
    "Safety Index": 23.89,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Trinidad And Tobago",
    "Crime Index": 73.19,
    "Safety Index": 26.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Brazil",
    "Crime Index": 68.88,
    "Safety Index": 31.12,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Peru",
    "Crime Index": 68.15,
    "Safety Index": 31.85,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "El Salvador",
    "Crime Index": 67.96,
    "Safety Index": 32.04,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Guyana",
    "Crime Index": 67.66,
    "Safety Index": 32.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Namibia",
    "Crime Index": 67.21,
    "Safety Index": 32.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Syria",
    "Crime Index": 66.46,
    "Safety Index": 33.54,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Jamaica",
    "Crime Index": 66.04,
    "Safety Index": 33.96,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Puerto Rico",
    "Crime Index": 65.63,
    "Safety Index": 34.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Angola",
    "Crime Index": 64.97,
    "Safety Index": 35.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bangladesh",
    "Crime Index": 63.94,
    "Safety Index": 36.06,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Nigeria",
    "Crime Index": 63.77,
    "Safety Index": 36.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bahamas",
    "Crime Index": 62.86,
    "Safety Index": 37.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Libya",
    "Crime Index": 62.19,
    "Safety Index": 37.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kazakhstan",
    "Crime Index": 62.02,
    "Safety Index": 37.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Argentina",
    "Crime Index": 61.77,
    "Safety Index": 38.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kenya",
    "Crime Index": 61.66,
    "Safety Index": 38.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Dominican Republic",
    "Crime Index": 61.16,
    "Safety Index": 38.84,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Uganda",
    "Crime Index": 59,
    "Safety Index": 41,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Tanzania",
    "Crime Index": 58.95,
    "Safety Index": 41.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Fiji",
    "Crime Index": 58.92,
    "Safety Index": 41.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Malaysia",
    "Crime Index": 58.84,
    "Safety Index": 41.16,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Somalia",
    "Crime Index": 58.5,
    "Safety Index": 41.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Mongolia",
    "Crime Index": 57.97,
    "Safety Index": 42.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Guatemala",
    "Crime Index": 57.83,
    "Safety Index": 42.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Zimbabwe",
    "Crime Index": 57.47,
    "Safety Index": 42.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Costa Rica",
    "Crime Index": 56.33,
    "Safety Index": 43.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Colombia",
    "Crime Index": 54.79,
    "Safety Index": 45.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Mexico",
    "Crime Index": 53.97,
    "Safety Index": 46.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Uruguay",
    "Crime Index": 53.81,
    "Safety Index": 46.19,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Botswana",
    "Crime Index": 53.49,
    "Safety Index": 46.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Maldives",
    "Crime Index": 53.21,
    "Safety Index": 46.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bolivia",
    "Crime Index": 52.93,
    "Safety Index": 47.07,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ecuador",
    "Crime Index": 50.9,
    "Safety Index": 49.1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Cambodia",
    "Crime Index": 50.66,
    "Safety Index": 49.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Algeria",
    "Crime Index": 49.81,
    "Safety Index": 50.19,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Paraguay",
    "Crime Index": 49.6,
    "Safety Index": 50.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iran",
    "Crime Index": 49.25,
    "Safety Index": 50.75,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ethiopia",
    "Crime Index": 49.21,
    "Safety Index": 50.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ghana",
    "Crime Index": 48.97,
    "Safety Index": 51.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ukraine",
    "Crime Index": 48.85,
    "Safety Index": 51.15,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Morocco",
    "Crime Index": 48.69,
    "Safety Index": 51.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iraq",
    "Crime Index": 47.78,
    "Safety Index": 52.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Mauritius",
    "Crime Index": 47.33,
    "Safety Index": 52.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United States",
    "Crime Index": 47.2,
    "Safety Index": 52.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Panama",
    "Crime Index": 47.19,
    "Safety Index": 52.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Sweden",
    "Crime Index": 47.07,
    "Safety Index": 52.93,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Egypt",
    "Crime Index": 46.92,
    "Safety Index": 53.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "France",
    "Crime Index": 46.79,
    "Safety Index": 53.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Myanmar",
    "Crime Index": 45.86,
    "Safety Index": 54.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Indonesia",
    "Crime Index": 45.84,
    "Safety Index": 54.16,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ireland",
    "Crime Index": 45.43,
    "Safety Index": 54.57,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Vietnam",
    "Crime Index": 45.35,
    "Safety Index": 54.65,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Chile",
    "Crime Index": 45.23,
    "Safety Index": 54.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Moldova",
    "Crime Index": 44.98,
    "Safety Index": 55.02,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Nicaragua",
    "Crime Index": 44.44,
    "Safety Index": 55.56,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Italy",
    "Crime Index": 44.26,
    "Safety Index": 55.74,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Pakistan",
    "Crime Index": 44.08,
    "Safety Index": 55.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Belgium",
    "Crime Index": 43.98,
    "Safety Index": 56.02,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United Kingdom",
    "Crime Index": 43.71,
    "Safety Index": 56.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Palestine",
    "Crime Index": 43.59,
    "Safety Index": 56.41,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Lebanon",
    "Crime Index": 43.36,
    "Safety Index": 56.64,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "India",
    "Crime Index": 43.32,
    "Safety Index": 56.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bosnia And Herzegovina",
    "Crime Index": 43.03,
    "Safety Index": 56.97,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Philippines",
    "Crime Index": 42.16,
    "Safety Index": 57.84,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Tunisia",
    "Crime Index": 41.88,
    "Safety Index": 58.12,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Australia",
    "Crime Index": 41.36,
    "Safety Index": 58.64,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Montenegro",
    "Crime Index": 41.18,
    "Safety Index": 58.82,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Russia",
    "Crime Index": 41.12,
    "Safety Index": 58.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "New Zealand",
    "Crime Index": 40.93,
    "Safety Index": 59.07,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Jordan",
    "Crime Index": 40.83,
    "Safety Index": 59.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Thailand",
    "Crime Index": 40.48,
    "Safety Index": 59.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Greece",
    "Crime Index": 40.32,
    "Safety Index": 59.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Sri Lanka",
    "Crime Index": 40.22,
    "Safety Index": 59.78,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Canada",
    "Crime Index": 39.67,
    "Safety Index": 60.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Albania",
    "Crime Index": 39.52,
    "Safety Index": 60.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Turkey",
    "Crime Index": 39.49,
    "Safety Index": 60.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Malta",
    "Crime Index": 39.04,
    "Safety Index": 60.96,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "North Macedonia",
    "Crime Index": 38.67,
    "Safety Index": 61.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bulgaria",
    "Crime Index": 38.5,
    "Safety Index": 61.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Serbia",
    "Crime Index": 37.41,
    "Safety Index": 62.59,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Latvia",
    "Crime Index": 36.95,
    "Safety Index": 63.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Norway",
    "Crime Index": 35.43,
    "Safety Index": 64.57,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Hungary",
    "Crime Index": 35.08,
    "Safety Index": 64.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Germany",
    "Crime Index": 34.81,
    "Safety Index": 65.19,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kuwait",
    "Crime Index": 34.75,
    "Safety Index": 65.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Nepal",
    "Crime Index": 34.56,
    "Safety Index": 65.44,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Luxembourg",
    "Crime Index": 33.39,
    "Safety Index": 66.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Lithuania",
    "Crime Index": 33.06,
    "Safety Index": 66.94,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kosovo (Disputed Territory)",
    "Crime Index": 32.91,
    "Safety Index": 67.09,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Spain",
    "Crime Index": 31.96,
    "Safety Index": 68.04,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "China",
    "Crime Index": 31.83,
    "Safety Index": 68.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Azerbaijan",
    "Crime Index": 31.61,
    "Safety Index": 68.39,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Singapore",
    "Crime Index": 30.57,
    "Safety Index": 69.43,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Cyprus",
    "Crime Index": 30.01,
    "Safety Index": 69.99,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Portugal",
    "Crime Index": 29.63,
    "Safety Index": 70.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Israel",
    "Crime Index": 29.6,
    "Safety Index": 70.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bahrain",
    "Crime Index": 29.29,
    "Safety Index": 70.71,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Slovakia",
    "Crime Index": 29.22,
    "Safety Index": 70.78,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Poland",
    "Crime Index": 28.5,
    "Safety Index": 71.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "South Korea",
    "Crime Index": 28.02,
    "Safety Index": 71.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Brunei",
    "Crime Index": 27.68,
    "Safety Index": 72.32,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Romania",
    "Crime Index": 27.64,
    "Safety Index": 72.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Netherlands",
    "Crime Index": 27.62,
    "Safety Index": 72.38,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Cuba",
    "Crime Index": 27.45,
    "Safety Index": 72.55,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Saudi Arabia",
    "Crime Index": 26.18,
    "Safety Index": 73.82,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Czech Republic",
    "Crime Index": 25.52,
    "Safety Index": 74.48,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Denmark",
    "Crime Index": 25.1,
    "Safety Index": 74.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Belarus",
    "Crime Index": 24.99,
    "Safety Index": 75.01,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Croatia",
    "Crime Index": 24.71,
    "Safety Index": 75.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Austria",
    "Crime Index": 23.73,
    "Safety Index": 76.27,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iceland",
    "Crime Index": 23.36,
    "Safety Index": 76.64,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Finland",
    "Crime Index": 23.32,
    "Safety Index": 76.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Estonia",
    "Crime Index": 23.14,
    "Safety Index": 76.86,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Armenia",
    "Crime Index": 21.6,
    "Safety Index": 78.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Switzerland",
    "Crime Index": 21.6,
    "Safety Index": 78.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Slovenia",
    "Crime Index": 21.07,
    "Safety Index": 78.93,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Oman",
    "Crime Index": 20.79,
    "Safety Index": 79.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Hong Kong",
    "Crime Index": 20.7,
    "Safety Index": 79.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Japan",
    "Crime Index": 20.66,
    "Safety Index": 79.34,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Georgia",
    "Crime Index": 20.21,
    "Safety Index": 79.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United Arab Emirates",
    "Crime Index": 15.7,
    "Safety Index": 84.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Taiwan",
    "Crime Index": 15.65,
    "Safety Index": 84.35,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Qatar",
    "Crime Index": 11.86,
    "Safety Index": 88.14,
  },
];
