module.exports = [
  {
    Country: "Taiwan",
    "Health Care Index": 86.71,
    "Health Care Exp. Index": 159.66,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "South Korea",
    "Health Care Index": 81.97,
    "Health Care Exp. Index": 149.94,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Japan",
    "Health Care Index": 81.14,
    "Health Care Exp. Index": 148.24,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Denmark",
    "Health Care Index": 80,
    "Health Care Exp. Index": 147.47,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "France",
    "Health Care Index": 79.99,
    "Health Care Exp. Index": 146.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Spain",
    "Health Care Index": 78.88,
    "Health Care Exp. Index": 145.24,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Austria",
    "Health Care Index": 78.73,
    "Health Care Exp. Index": 144.24,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Thailand",
    "Health Care Index": 77.95,
    "Health Care Exp. Index": 142.04,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Australia",
    "Health Care Index": 77.38,
    "Health Care Exp. Index": 140.97,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Finland",
    "Health Care Index": 75.79,
    "Health Care Exp. Index": 138.01,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Netherlands",
    "Health Care Index": 74.65,
    "Health Care Exp. Index": 136.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Czech Republic",
    "Health Care Index": 74.62,
    "Health Care Exp. Index": 136.97,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United Kingdom",
    "Health Care Index": 74.46,
    "Health Care Exp. Index": 136.57,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Norway",
    "Health Care Index": 74.36,
    "Health Care Exp. Index": 135.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Belgium",
    "Health Care Index": 74.34,
    "Health Care Exp. Index": 134.81,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "New Zealand",
    "Health Care Index": 73.81,
    "Health Care Exp. Index": 133.94,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Germany",
    "Health Care Index": 73.32,
    "Health Care Exp. Index": 133.56,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Qatar",
    "Health Care Index": 73.3,
    "Health Care Exp. Index": 133.07,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Israel",
    "Health Care Index": 73.29,
    "Health Care Exp. Index": 134.31,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Estonia",
    "Health Care Index": 72.67,
    "Health Care Exp. Index": 132.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Sri Lanka",
    "Health Care Index": 72.53,
    "Health Care Exp. Index": 131.07,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Switzerland",
    "Health Care Index": 72.44,
    "Health Care Exp. Index": 136.25,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Portugal",
    "Health Care Index": 71.88,
    "Health Care Exp. Index": 130.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Canada",
    "Health Care Index": 71.58,
    "Health Care Exp. Index": 131.44,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Singapore",
    "Health Care Index": 70.84,
    "Health Care Exp. Index": 131.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ecuador",
    "Health Care Index": 70.59,
    "Health Care Exp. Index": 126.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Mexico",
    "Health Care Index": 70.12,
    "Health Care Exp. Index": 125.71,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Turkey",
    "Health Care Index": 69.8,
    "Health Care Exp. Index": 125.57,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Lithuania",
    "Health Care Index": 69.49,
    "Health Care Exp. Index": 125.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United States",
    "Health Care Index": 69.27,
    "Health Care Exp. Index": 127.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Argentina",
    "Health Care Index": 69.25,
    "Health Care Exp. Index": 125.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Sweden",
    "Health Care Index": 69.23,
    "Health Care Exp. Index": 126.86,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Malta",
    "Health Care Index": 68.81,
    "Health Care Exp. Index": 123.37,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Malaysia",
    "Health Care Index": 68.1,
    "Health Care Exp. Index": 122.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Guatemala",
    "Health Care Index": 67.75,
    "Health Care Exp. Index": 121.19,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Philippines",
    "Health Care Index": 67.47,
    "Health Care Exp. Index": 120.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Colombia",
    "Health Care Index": 67.24,
    "Health Care Exp. Index": 120.65,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "India",
    "Health Care Index": 67.13,
    "Health Care Exp. Index": 120.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United Arab Emirates",
    "Health Care Index": 67.04,
    "Health Care Exp. Index": 123.91,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Italy",
    "Health Care Index": 66.59,
    "Health Care Exp. Index": 120.66,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Uruguay",
    "Health Care Index": 66.28,
    "Health Care Exp. Index": 119.62,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Hong Kong",
    "Health Care Index": 66.08,
    "Health Care Exp. Index": 119.75,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iceland",
    "Health Care Index": 65.92,
    "Health Care Exp. Index": 120.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Chile",
    "Health Care Index": 65.44,
    "Health Care Exp. Index": 118.89,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Jordan",
    "Health Care Index": 64.6,
    "Health Care Exp. Index": 116.14,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Slovenia",
    "Health Care Index": 64.58,
    "Health Care Exp. Index": 118.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "China",
    "Health Care Index": 64.48,
    "Health Care Exp. Index": 115.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Lebanon",
    "Health Care Index": 64.38,
    "Health Care Exp. Index": 120.05,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "South Africa",
    "Health Care Index": 64.14,
    "Health Care Exp. Index": 115.76,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Latvia",
    "Health Care Index": 62.91,
    "Health Care Exp. Index": 113.01,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Croatia",
    "Health Care Index": 62.68,
    "Health Care Exp. Index": 115.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Costa Rica",
    "Health Care Index": 62.42,
    "Health Care Exp. Index": 112.66,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Poland",
    "Health Care Index": 61.01,
    "Health Care Exp. Index": 109.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Pakistan",
    "Health Care Index": 60.59,
    "Health Care Exp. Index": 107.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Indonesia",
    "Health Care Index": 60.48,
    "Health Care Exp. Index": 107.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Slovakia",
    "Health Care Index": 60.02,
    "Health Care Exp. Index": 108.64,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Panama",
    "Health Care Index": 59.93,
    "Health Care Exp. Index": 106.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Saudi Arabia",
    "Health Care Index": 59.11,
    "Health Care Exp. Index": 105.18,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Belarus",
    "Health Care Index": 59.04,
    "Health Care Exp. Index": 105.39,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Oman",
    "Health Care Index": 58.15,
    "Health Care Exp. Index": 103.73,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Vietnam",
    "Health Care Index": 57.7,
    "Health Care Exp. Index": 100.69,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Russia",
    "Health Care Index": 57.59,
    "Health Care Exp. Index": 101.55,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Tunisia",
    "Health Care Index": 57.18,
    "Health Care Exp. Index": 100.55,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Nepal",
    "Health Care Index": 56.88,
    "Health Care Exp. Index": 99.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "North Macedonia",
    "Health Care Index": 56.38,
    "Health Care Exp. Index": 100.54,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Brazil",
    "Health Care Index": 56.29,
    "Health Care Exp. Index": 100.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Greece",
    "Health Care Index": 56.21,
    "Health Care Exp. Index": 99.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kuwait",
    "Health Care Index": 56.21,
    "Health Care Exp. Index": 100.47,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Peru",
    "Health Care Index": 56.15,
    "Health Care Exp. Index": 98.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Puerto Rico",
    "Health Care Index": 55.73,
    "Health Care Exp. Index": 101.76,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kenya",
    "Health Care Index": 55.59,
    "Health Care Exp. Index": 98.02,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bulgaria",
    "Health Care Index": 55.4,
    "Health Care Exp. Index": 98.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Romania",
    "Health Care Index": 55.06,
    "Health Care Exp. Index": 96.89,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Algeria",
    "Health Care Index": 54.86,
    "Health Care Exp. Index": 99.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Trinidad And Tobago",
    "Health Care Index": 54.73,
    "Health Care Exp. Index": 100.89,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Dominican Republic",
    "Health Care Index": 54.67,
    "Health Care Exp. Index": 95.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Albania",
    "Health Care Index": 53.05,
    "Health Care Exp. Index": 92.72,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ukraine",
    "Health Care Index": 52.33,
    "Health Care Exp. Index": 91.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bosnia And Herzegovina",
    "Health Care Index": 52.26,
    "Health Care Exp. Index": 93.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ireland",
    "Health Care Index": 51.89,
    "Health Care Exp. Index": 94.23,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Cyprus",
    "Health Care Index": 51.75,
    "Health Care Exp. Index": 89.36,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iran",
    "Health Care Index": 51.7,
    "Health Care Exp. Index": 90.06,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Nigeria",
    "Health Care Index": 51.59,
    "Health Care Exp. Index": 89.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Serbia",
    "Health Care Index": 51.27,
    "Health Care Exp. Index": 92.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Georgia",
    "Health Care Index": 51.24,
    "Health Care Exp. Index": 88.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kazakhstan",
    "Health Care Index": 50.7,
    "Health Care Exp. Index": 88.95,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Hungary",
    "Health Care Index": 47.8,
    "Health Care Exp. Index": 86.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Egypt",
    "Health Care Index": 45.84,
    "Health Care Exp. Index": 78.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Morocco",
    "Health Care Index": 45.72,
    "Health Care Exp. Index": 77.88,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Azerbaijan",
    "Health Care Index": 43.18,
    "Health Care Exp. Index": 74.96,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bangladesh",
    "Health Care Index": 42.8,
    "Health Care Exp. Index": 73.17,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iraq",
    "Health Care Index": 41.36,
    "Health Care Exp. Index": 70.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Venezuela",
    "Health Care Index": 39.66,
    "Health Care Exp. Index": 69.14,
  },
];
