module.exports = [
  {
    Country: "Venezuela",
    "Price To Income Ratio": 133.29,
    "Gross Rental Yield City Centre": 6.22,
    "Gross Rental Yield Outside of Centre": 6.45,
    "Price To Rent Ratio City Centre": 16.08,
    "Price To Rent Ratio Outside Of City Centre": 15.49,
    "Mortgage As A Percentage Of Income": 3025.03,
    "Affordability Index": 0.03,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Syria",
    "Price To Income Ratio": 60.83,
    "Gross Rental Yield City Centre": 2.71,
    "Gross Rental Yield Outside of Centre": 3,
    "Price To Rent Ratio City Centre": 36.93,
    "Price To Rent Ratio Outside Of City Centre": 33.29,
    "Mortgage As A Percentage Of Income": 662.83,
    "Affordability Index": 0.15,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Hong Kong",
    "Price To Income Ratio": 47.46,
    "Gross Rental Yield City Centre": 1.77,
    "Gross Rental Yield Outside of Centre": 1.83,
    "Price To Rent Ratio City Centre": 56.45,
    "Price To Rent Ratio Outside Of City Centre": 54.74,
    "Mortgage As A Percentage Of Income": 303.35,
    "Affordability Index": 0.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Cambodia",
    "Price To Income Ratio": 42.33,
    "Gross Rental Yield City Centre": 4.78,
    "Gross Rental Yield Outside of Centre": 6.2,
    "Price To Rent Ratio City Centre": 20.93,
    "Price To Rent Ratio Outside Of City Centre": 16.13,
    "Mortgage As A Percentage Of Income": 479.45,
    "Affordability Index": 0.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kenya",
    "Price To Income Ratio": 31.63,
    "Gross Rental Yield City Centre": 2.15,
    "Gross Rental Yield Outside of Centre": 4.07,
    "Price To Rent Ratio City Centre": 46.56,
    "Price To Rent Ratio Outside Of City Centre": 24.54,
    "Mortgage As A Percentage Of Income": 472.19,
    "Affordability Index": 0.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Sri Lanka",
    "Price To Income Ratio": 31.14,
    "Gross Rental Yield City Centre": 2.88,
    "Gross Rental Yield Outside of Centre": 2.36,
    "Price To Rent Ratio City Centre": 34.76,
    "Price To Rent Ratio Outside Of City Centre": 42.32,
    "Mortgage As A Percentage Of Income": 478.77,
    "Affordability Index": 0.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "China",
    "Price To Income Ratio": 29.06,
    "Gross Rental Yield City Centre": 1.71,
    "Gross Rental Yield Outside of Centre": 1.91,
    "Price To Rent Ratio City Centre": 58.34,
    "Price To Rent Ratio Outside Of City Centre": 52.38,
    "Mortgage As A Percentage Of Income": 231.68,
    "Affordability Index": 0.43,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iran",
    "Price To Income Ratio": 25.11,
    "Gross Rental Yield City Centre": 4.92,
    "Gross Rental Yield Outside of Centre": 5.43,
    "Price To Rent Ratio City Centre": 20.33,
    "Price To Rent Ratio Outside Of City Centre": 18.41,
    "Mortgage As A Percentage Of Income": 515.47,
    "Affordability Index": 0.19,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Nepal",
    "Price To Income Ratio": 24.74,
    "Gross Rental Yield City Centre": 2.57,
    "Gross Rental Yield Outside of Centre": 3.23,
    "Price To Rent Ratio City Centre": 38.9,
    "Price To Rent Ratio Outside Of City Centre": 30.95,
    "Mortgage As A Percentage Of Income": 314.15,
    "Affordability Index": 0.32,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Philippines",
    "Price To Income Ratio": 24.6,
    "Gross Rental Yield City Centre": 3.44,
    "Gross Rental Yield Outside of Centre": 3.95,
    "Price To Rent Ratio City Centre": 29.04,
    "Price To Rent Ratio Outside Of City Centre": 25.35,
    "Mortgage As A Percentage Of Income": 237.12,
    "Affordability Index": 0.42,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Argentina",
    "Price To Income Ratio": 24.53,
    "Gross Rental Yield City Centre": 1.93,
    "Gross Rental Yield Outside of Centre": 1.95,
    "Price To Rent Ratio City Centre": 51.89,
    "Price To Rent Ratio Outside Of City Centre": 51.32,
    "Mortgage As A Percentage Of Income": 1041.24,
    "Affordability Index": 0.1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Taiwan",
    "Price To Income Ratio": 23.69,
    "Gross Rental Yield City Centre": 1.38,
    "Gross Rental Yield Outside of Centre": 1.5,
    "Price To Rent Ratio City Centre": 72.61,
    "Price To Rent Ratio Outside Of City Centre": 66.6,
    "Mortgage As A Percentage Of Income": 142.46,
    "Affordability Index": 0.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Singapore",
    "Price To Income Ratio": 22.31,
    "Gross Rental Yield City Centre": 2.32,
    "Gross Rental Yield Outside of Centre": 2.78,
    "Price To Rent Ratio City Centre": 43.02,
    "Price To Rent Ratio Outside Of City Centre": 35.96,
    "Mortgage As A Percentage Of Income": 142.09,
    "Affordability Index": 0.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Thailand",
    "Price To Income Ratio": 22.26,
    "Gross Rental Yield City Centre": 3.22,
    "Gross Rental Yield Outside of Centre": 3.72,
    "Price To Rent Ratio City Centre": 31.02,
    "Price To Rent Ratio Outside Of City Centre": 26.9,
    "Mortgage As A Percentage Of Income": 185.69,
    "Affordability Index": 0.54,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Vietnam",
    "Price To Income Ratio": 21.36,
    "Gross Rental Yield City Centre": 4.23,
    "Gross Rental Yield Outside of Centre": 5.55,
    "Price To Rent Ratio City Centre": 23.65,
    "Price To Rent Ratio Outside Of City Centre": 18.02,
    "Mortgage As A Percentage Of Income": 228.46,
    "Affordability Index": 0.44,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Colombia",
    "Price To Income Ratio": 19.65,
    "Gross Rental Yield City Centre": 4.53,
    "Gross Rental Yield Outside of Centre": 4.09,
    "Price To Rent Ratio City Centre": 22.08,
    "Price To Rent Ratio Outside Of City Centre": 24.45,
    "Mortgage As A Percentage Of Income": 255.62,
    "Affordability Index": 0.39,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Serbia",
    "Price To Income Ratio": 18.94,
    "Gross Rental Yield City Centre": 3.09,
    "Gross Rental Yield Outside of Centre": 3.42,
    "Price To Rent Ratio City Centre": 32.33,
    "Price To Rent Ratio Outside Of City Centre": 29.26,
    "Mortgage As A Percentage Of Income": 135.81,
    "Affordability Index": 0.74,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Indonesia",
    "Price To Income Ratio": 18.88,
    "Gross Rental Yield City Centre": 4.77,
    "Gross Rental Yield Outside of Centre": 5.08,
    "Price To Rent Ratio City Centre": 20.95,
    "Price To Rent Ratio Outside Of City Centre": 19.67,
    "Mortgage As A Percentage Of Income": 220.84,
    "Affordability Index": 0.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Algeria",
    "Price To Income Ratio": 17.81,
    "Gross Rental Yield City Centre": 3,
    "Gross Rental Yield Outside of Centre": 3.81,
    "Price To Rent Ratio City Centre": 33.29,
    "Price To Rent Ratio Outside Of City Centre": 26.21,
    "Mortgage As A Percentage Of Income": 150.28,
    "Affordability Index": 0.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "South Korea",
    "Price To Income Ratio": 17.37,
    "Gross Rental Yield City Centre": 1.48,
    "Gross Rental Yield Outside of Centre": 1.79,
    "Price To Rent Ratio City Centre": 67.35,
    "Price To Rent Ratio Outside Of City Centre": 55.91,
    "Mortgage As A Percentage Of Income": 121.78,
    "Affordability Index": 0.82,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Armenia",
    "Price To Income Ratio": 16.62,
    "Gross Rental Yield City Centre": 5.84,
    "Gross Rental Yield Outside of Centre": 5.75,
    "Price To Rent Ratio City Centre": 17.12,
    "Price To Rent Ratio Outside Of City Centre": 17.4,
    "Mortgage As A Percentage Of Income": 213.97,
    "Affordability Index": 0.47,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Brazil",
    "Price To Income Ratio": 16.41,
    "Gross Rental Yield City Centre": 4.11,
    "Gross Rental Yield Outside of Centre": 4.32,
    "Price To Rent Ratio City Centre": 24.32,
    "Price To Rent Ratio Outside Of City Centre": 23.16,
    "Mortgage As A Percentage Of Income": 188.61,
    "Affordability Index": 0.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Uruguay",
    "Price To Income Ratio": 16.34,
    "Gross Rental Yield City Centre": 3.97,
    "Gross Rental Yield Outside of Centre": 4.05,
    "Price To Rent Ratio City Centre": 25.21,
    "Price To Rent Ratio Outside Of City Centre": 24.7,
    "Mortgage As A Percentage Of Income": 165.87,
    "Affordability Index": 0.6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Azerbaijan",
    "Price To Income Ratio": 16.24,
    "Gross Rental Yield City Centre": 5.25,
    "Gross Rental Yield Outside of Centre": 5.43,
    "Price To Rent Ratio City Centre": 19.05,
    "Price To Rent Ratio Outside Of City Centre": 18.4,
    "Mortgage As A Percentage Of Income": 165.33,
    "Affordability Index": 0.6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Albania",
    "Price To Income Ratio": 15.49,
    "Gross Rental Yield City Centre": 4.2,
    "Gross Rental Yield Outside of Centre": 5.3,
    "Price To Rent Ratio City Centre": 23.82,
    "Price To Rent Ratio Outside Of City Centre": 18.86,
    "Mortgage As A Percentage Of Income": 125.86,
    "Affordability Index": 0.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Czech Republic",
    "Price To Income Ratio": 15.42,
    "Gross Rental Yield City Centre": 3.32,
    "Gross Rental Yield Outside of Centre": 3.65,
    "Price To Rent Ratio City Centre": 30.08,
    "Price To Rent Ratio Outside Of City Centre": 27.37,
    "Mortgage As A Percentage Of Income": 99.53,
    "Affordability Index": 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Uzbekistan",
    "Price To Income Ratio": 15.31,
    "Gross Rental Yield City Centre": 6.11,
    "Gross Rental Yield Outside of Centre": 7.23,
    "Price To Rent Ratio City Centre": 16.36,
    "Price To Rent Ratio Outside Of City Centre": 13.82,
    "Mortgage As A Percentage Of Income": 288.74,
    "Affordability Index": 0.35,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Peru",
    "Price To Income Ratio": 14.95,
    "Gross Rental Yield City Centre": 5.48,
    "Gross Rental Yield Outside of Centre": 5.08,
    "Price To Rent Ratio City Centre": 18.24,
    "Price To Rent Ratio Outside Of City Centre": 19.68,
    "Mortgage As A Percentage Of Income": 162.85,
    "Affordability Index": 0.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Chile",
    "Price To Income Ratio": 14.93,
    "Gross Rental Yield City Centre": 4.34,
    "Gross Rental Yield Outside of Centre": 3.89,
    "Price To Rent Ratio City Centre": 23.02,
    "Price To Rent Ratio Outside Of City Centre": 25.69,
    "Mortgage As A Percentage Of Income": 106.28,
    "Affordability Index": 0.94,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Hungary",
    "Price To Income Ratio": 14.77,
    "Gross Rental Yield City Centre": 3.8,
    "Gross Rental Yield Outside of Centre": 4.27,
    "Price To Rent Ratio City Centre": 26.31,
    "Price To Rent Ratio Outside Of City Centre": 23.4,
    "Mortgage As A Percentage Of Income": 116.46,
    "Affordability Index": 0.86,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Belarus",
    "Price To Income Ratio": 14.65,
    "Gross Rental Yield City Centre": 5.03,
    "Gross Rental Yield Outside of Centre": 4.62,
    "Price To Rent Ratio City Centre": 19.86,
    "Price To Rent Ratio Outside Of City Centre": 21.63,
    "Mortgage As A Percentage Of Income": 223.16,
    "Affordability Index": 0.45,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Georgia",
    "Price To Income Ratio": 14.21,
    "Gross Rental Yield City Centre": 7.63,
    "Gross Rental Yield Outside of Centre": 8.51,
    "Price To Rent Ratio City Centre": 13.11,
    "Price To Rent Ratio Outside Of City Centre": 11.75,
    "Mortgage As A Percentage Of Income": 196.1,
    "Affordability Index": 0.51,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Morocco",
    "Price To Income Ratio": 14.18,
    "Gross Rental Yield City Centre": 4.49,
    "Gross Rental Yield Outside of Centre": 4.66,
    "Price To Rent Ratio City Centre": 22.27,
    "Price To Rent Ratio Outside Of City Centre": 21.47,
    "Mortgage As A Percentage Of Income": 114.32,
    "Affordability Index": 0.87,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Croatia",
    "Price To Income Ratio": 13.73,
    "Gross Rental Yield City Centre": 3.41,
    "Gross Rental Yield Outside of Centre": 3.55,
    "Price To Rent Ratio City Centre": 29.28,
    "Price To Rent Ratio Outside Of City Centre": 28.2,
    "Mortgage As A Percentage Of Income": 101.72,
    "Affordability Index": 0.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Dominican Republic",
    "Price To Income Ratio": 13.48,
    "Gross Rental Yield City Centre": 6.69,
    "Gross Rental Yield Outside of Centre": 6.49,
    "Price To Rent Ratio City Centre": 14.95,
    "Price To Rent Ratio Outside Of City Centre": 15.4,
    "Mortgage As A Percentage Of Income": 183.43,
    "Affordability Index": 0.55,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Montenegro",
    "Price To Income Ratio": 13.23,
    "Gross Rental Yield City Centre": 4.57,
    "Gross Rental Yield Outside of Centre": 4.37,
    "Price To Rent Ratio City Centre": 21.9,
    "Price To Rent Ratio Outside Of City Centre": 22.9,
    "Mortgage As A Percentage Of Income": 117.5,
    "Affordability Index": 0.85,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Lebanon",
    "Price To Income Ratio": 13.23,
    "Gross Rental Yield City Centre": 5.06,
    "Gross Rental Yield Outside of Centre": 5.81,
    "Price To Rent Ratio City Centre": 19.77,
    "Price To Rent Ratio Outside Of City Centre": 17.21,
    "Mortgage As A Percentage Of Income": 122.53,
    "Affordability Index": 0.82,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bangladesh",
    "Price To Income Ratio": 13.1,
    "Gross Rental Yield City Centre": 2.91,
    "Gross Rental Yield Outside of Centre": 3.69,
    "Price To Rent Ratio City Centre": 34.41,
    "Price To Rent Ratio Outside Of City Centre": 27.09,
    "Mortgage As A Percentage Of Income": 163.36,
    "Affordability Index": 0.61,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "France",
    "Price To Income Ratio": 13.04,
    "Gross Rental Yield City Centre": 2.44,
    "Gross Rental Yield Outside of Centre": 3.02,
    "Price To Rent Ratio City Centre": 41,
    "Price To Rent Ratio Outside Of City Centre": 33.08,
    "Mortgage As A Percentage Of Income": 76.69,
    "Affordability Index": 1.3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Egypt",
    "Price To Income Ratio": 13.01,
    "Gross Rental Yield City Centre": 5.57,
    "Gross Rental Yield Outside of Centre": 6.23,
    "Price To Rent Ratio City Centre": 17.96,
    "Price To Rent Ratio Outside Of City Centre": 16.04,
    "Mortgage As A Percentage Of Income": 193.89,
    "Affordability Index": 0.52,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Japan",
    "Price To Income Ratio": 13,
    "Gross Rental Yield City Centre": 2.11,
    "Gross Rental Yield Outside of Centre": 2.56,
    "Price To Rent Ratio City Centre": 47.39,
    "Price To Rent Ratio Outside Of City Centre": 39,
    "Mortgage As A Percentage Of Income": 75.15,
    "Affordability Index": 1.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Israel",
    "Price To Income Ratio": 12.83,
    "Gross Rental Yield City Centre": 3.2,
    "Gross Rental Yield Outside of Centre": 3.1,
    "Price To Rent Ratio City Centre": 31.21,
    "Price To Rent Ratio Outside Of City Centre": 32.25,
    "Mortgage As A Percentage Of Income": 90.29,
    "Affordability Index": 1.11,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ecuador",
    "Price To Income Ratio": 12.7,
    "Gross Rental Yield City Centre": 5.53,
    "Gross Rental Yield Outside of Centre": 5.4,
    "Price To Rent Ratio City Centre": 18.08,
    "Price To Rent Ratio Outside Of City Centre": 18.52,
    "Mortgage As A Percentage Of Income": 150.75,
    "Affordability Index": 0.66,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Portugal",
    "Price To Income Ratio": 12.7,
    "Gross Rental Yield City Centre": 5.04,
    "Gross Rental Yield Outside of Centre": 6.11,
    "Price To Rent Ratio City Centre": 19.85,
    "Price To Rent Ratio Outside Of City Centre": 16.38,
    "Mortgage As A Percentage Of Income": 79.24,
    "Affordability Index": 1.26,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Panama",
    "Price To Income Ratio": 12.6,
    "Gross Rental Yield City Centre": 8.18,
    "Gross Rental Yield Outside of Centre": 8.02,
    "Price To Rent Ratio City Centre": 12.22,
    "Price To Rent Ratio Outside Of City Centre": 12.47,
    "Mortgage As A Percentage Of Income": 101.92,
    "Affordability Index": 0.98,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "North Macedonia",
    "Price To Income Ratio": 12.6,
    "Gross Rental Yield City Centre": 4.01,
    "Gross Rental Yield Outside of Centre": 4.02,
    "Price To Rent Ratio City Centre": 24.93,
    "Price To Rent Ratio Outside Of City Centre": 24.85,
    "Mortgage As A Percentage Of Income": 106.11,
    "Affordability Index": 0.94,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bosnia And Herzegovina",
    "Price To Income Ratio": 12.58,
    "Gross Rental Yield City Centre": 3.36,
    "Gross Rental Yield Outside of Centre": 3.22,
    "Price To Rent Ratio City Centre": 29.73,
    "Price To Rent Ratio Outside Of City Centre": 31.08,
    "Mortgage As A Percentage Of Income": 98.12,
    "Affordability Index": 1.02,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Malta",
    "Price To Income Ratio": 12.32,
    "Gross Rental Yield City Centre": 5.69,
    "Gross Rental Yield Outside of Centre": 7.01,
    "Price To Rent Ratio City Centre": 17.57,
    "Price To Rent Ratio Outside Of City Centre": 14.26,
    "Mortgage As A Percentage Of Income": 90.4,
    "Affordability Index": 1.11,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kuwait",
    "Price To Income Ratio": 12.28,
    "Gross Rental Yield City Centre": 3.38,
    "Gross Rental Yield Outside of Centre": 5.26,
    "Price To Rent Ratio City Centre": 29.56,
    "Price To Rent Ratio Outside Of City Centre": 19.02,
    "Mortgage As A Percentage Of Income": 100.31,
    "Affordability Index": 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ukraine",
    "Price To Income Ratio": 12.23,
    "Gross Rental Yield City Centre": 6.47,
    "Gross Rental Yield Outside of Centre": 7.5,
    "Price To Rent Ratio City Centre": 15.46,
    "Price To Rent Ratio Outside Of City Centre": 13.33,
    "Mortgage As A Percentage Of Income": 243.98,
    "Affordability Index": 0.41,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Pakistan",
    "Price To Income Ratio": 11.98,
    "Gross Rental Yield City Centre": 4.87,
    "Gross Rental Yield Outside of Centre": 5.27,
    "Price To Rent Ratio City Centre": 20.54,
    "Price To Rent Ratio Outside Of City Centre": 18.98,
    "Mortgage As A Percentage Of Income": 178.79,
    "Affordability Index": 0.56,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Luxembourg",
    "Price To Income Ratio": 11.61,
    "Gross Rental Yield City Centre": 3.52,
    "Gross Rental Yield Outside of Centre": 4.01,
    "Price To Rent Ratio City Centre": 28.37,
    "Price To Rent Ratio Outside Of City Centre": 24.92,
    "Mortgage As A Percentage Of Income": 69.7,
    "Affordability Index": 1.43,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Poland",
    "Price To Income Ratio": 11.38,
    "Gross Rental Yield City Centre": 4.46,
    "Gross Rental Yield Outside of Centre": 4.94,
    "Price To Rent Ratio City Centre": 22.45,
    "Price To Rent Ratio Outside Of City Centre": 20.24,
    "Mortgage As A Percentage Of Income": 82.23,
    "Affordability Index": 1.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "India",
    "Price To Income Ratio": 11.38,
    "Gross Rental Yield City Centre": 2.99,
    "Gross Rental Yield Outside of Centre": 3.59,
    "Price To Rent Ratio City Centre": 33.46,
    "Price To Rent Ratio Outside Of City Centre": 27.84,
    "Mortgage As A Percentage Of Income": 126.19,
    "Affordability Index": 0.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Romania",
    "Price To Income Ratio": 11.33,
    "Gross Rental Yield City Centre": 4.4,
    "Gross Rental Yield Outside of Centre": 4.52,
    "Price To Rent Ratio City Centre": 22.73,
    "Price To Rent Ratio Outside Of City Centre": 22.11,
    "Mortgage As A Percentage Of Income": 94.22,
    "Affordability Index": 1.06,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Lithuania",
    "Price To Income Ratio": 10.9,
    "Gross Rental Yield City Centre": 4.09,
    "Gross Rental Yield Outside of Centre": 4.33,
    "Price To Rent Ratio City Centre": 24.43,
    "Price To Rent Ratio Outside Of City Centre": 23.09,
    "Mortgage As A Percentage Of Income": 68.53,
    "Affordability Index": 1.46,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Austria",
    "Price To Income Ratio": 10.88,
    "Gross Rental Yield City Centre": 3.28,
    "Gross Rental Yield Outside of Centre": 3.59,
    "Price To Rent Ratio City Centre": 30.53,
    "Price To Rent Ratio Outside Of City Centre": 27.83,
    "Mortgage As A Percentage Of Income": 66.86,
    "Affordability Index": 1.5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kazakhstan",
    "Price To Income Ratio": 10.86,
    "Gross Rental Yield City Centre": 6.47,
    "Gross Rental Yield Outside of Centre": 5.98,
    "Price To Rent Ratio City Centre": 15.45,
    "Price To Rent Ratio Outside Of City Centre": 16.72,
    "Mortgage As A Percentage Of Income": 176.94,
    "Affordability Index": 0.57,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Russia",
    "Price To Income Ratio": 10.77,
    "Gross Rental Yield City Centre": 5.89,
    "Gross Rental Yield Outside of Centre": 5.95,
    "Price To Rent Ratio City Centre": 16.99,
    "Price To Rent Ratio Outside Of City Centre": 16.82,
    "Mortgage As A Percentage Of Income": 129.82,
    "Affordability Index": 0.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Honduras",
    "Price To Income Ratio": 10.77,
    "Gross Rental Yield City Centre": 7.41,
    "Gross Rental Yield Outside of Centre": 6.29,
    "Price To Rent Ratio City Centre": 13.5,
    "Price To Rent Ratio Outside Of City Centre": 15.89,
    "Mortgage As A Percentage Of Income": 130.96,
    "Affordability Index": 0.76,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Kosovo (Disputed Territory)",
    "Price To Income Ratio": 10.67,
    "Gross Rental Yield City Centre": 4.79,
    "Gross Rental Yield Outside of Centre": 5.2,
    "Price To Rent Ratio City Centre": 20.89,
    "Price To Rent Ratio Outside Of City Centre": 19.23,
    "Mortgage As A Percentage Of Income": 82.59,
    "Affordability Index": 1.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Mexico",
    "Price To Income Ratio": 10.67,
    "Gross Rental Yield City Centre": 5.87,
    "Gross Rental Yield Outside of Centre": 5.78,
    "Price To Rent Ratio City Centre": 17.03,
    "Price To Rent Ratio Outside Of City Centre": 17.3,
    "Mortgage As A Percentage Of Income": 132.75,
    "Affordability Index": 0.75,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Tunisia",
    "Price To Income Ratio": 10.63,
    "Gross Rental Yield City Centre": 5.03,
    "Gross Rental Yield Outside of Centre": 5.16,
    "Price To Rent Ratio City Centre": 19.89,
    "Price To Rent Ratio Outside Of City Centre": 19.37,
    "Mortgage As A Percentage Of Income": 109.19,
    "Affordability Index": 0.92,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Greece",
    "Price To Income Ratio": 10.6,
    "Gross Rental Yield City Centre": 4.22,
    "Gross Rental Yield Outside of Centre": 4.09,
    "Price To Rent Ratio City Centre": 23.68,
    "Price To Rent Ratio Outside Of City Centre": 24.45,
    "Mortgage As A Percentage Of Income": 81.95,
    "Affordability Index": 1.22,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Slovenia",
    "Price To Income Ratio": 10.49,
    "Gross Rental Yield City Centre": 3.83,
    "Gross Rental Yield Outside of Centre": 3.91,
    "Price To Rent Ratio City Centre": 26.12,
    "Price To Rent Ratio Outside Of City Centre": 25.59,
    "Mortgage As A Percentage Of Income": 71.56,
    "Affordability Index": 1.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Costa Rica",
    "Price To Income Ratio": 10.31,
    "Gross Rental Yield City Centre": 5.96,
    "Gross Rental Yield Outside of Centre": 5.21,
    "Price To Rent Ratio City Centre": 16.79,
    "Price To Rent Ratio Outside Of City Centre": 19.2,
    "Mortgage As A Percentage Of Income": 119.42,
    "Affordability Index": 0.84,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Slovakia",
    "Price To Income Ratio": 10.25,
    "Gross Rental Yield City Centre": 5.1,
    "Gross Rental Yield Outside of Centre": 5.43,
    "Price To Rent Ratio City Centre": 19.6,
    "Price To Rent Ratio Outside Of City Centre": 18.42,
    "Mortgage As A Percentage Of Income": 60.15,
    "Affordability Index": 1.66,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United Kingdom",
    "Price To Income Ratio": 10.09,
    "Gross Rental Yield City Centre": 3.52,
    "Gross Rental Yield Outside of Centre": 4.11,
    "Price To Rent Ratio City Centre": 28.45,
    "Price To Rent Ratio Outside Of City Centre": 24.33,
    "Mortgage As A Percentage Of Income": 68.71,
    "Affordability Index": 1.46,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Guatemala",
    "Price To Income Ratio": 10.08,
    "Gross Rental Yield City Centre": 7.12,
    "Gross Rental Yield Outside of Centre": 7.51,
    "Price To Rent Ratio City Centre": 14.05,
    "Price To Rent Ratio Outside Of City Centre": 13.31,
    "Mortgage As A Percentage Of Income": 98.73,
    "Affordability Index": 1.01,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Malaysia",
    "Price To Income Ratio": 9.94,
    "Gross Rental Yield City Centre": 3.67,
    "Gross Rental Yield Outside of Centre": 3.94,
    "Price To Rent Ratio City Centre": 27.27,
    "Price To Rent Ratio Outside Of City Centre": 25.41,
    "Mortgage As A Percentage Of Income": 75.44,
    "Affordability Index": 1.33,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Italy",
    "Price To Income Ratio": 9.71,
    "Gross Rental Yield City Centre": 3.86,
    "Gross Rental Yield Outside of Centre": 4.78,
    "Price To Rent Ratio City Centre": 25.92,
    "Price To Rent Ratio Outside Of City Centre": 20.94,
    "Mortgage As A Percentage Of Income": 59.11,
    "Affordability Index": 1.69,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bolivia",
    "Price To Income Ratio": 9.69,
    "Gross Rental Yield City Centre": 6.87,
    "Gross Rental Yield Outside of Centre": 6.94,
    "Price To Rent Ratio City Centre": 14.56,
    "Price To Rent Ratio Outside Of City Centre": 14.4,
    "Mortgage As A Percentage Of Income": 100.09,
    "Affordability Index": 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Germany",
    "Price To Income Ratio": 9.38,
    "Gross Rental Yield City Centre": 3.22,
    "Gross Rental Yield Outside of Centre": 3.54,
    "Price To Rent Ratio City Centre": 31.01,
    "Price To Rent Ratio Outside Of City Centre": 28.25,
    "Mortgage As A Percentage Of Income": 56.33,
    "Affordability Index": 1.78,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Spain",
    "Price To Income Ratio": 9.37,
    "Gross Rental Yield City Centre": 4.64,
    "Gross Rental Yield Outside of Centre": 5.21,
    "Price To Rent Ratio City Centre": 21.55,
    "Price To Rent Ratio Outside Of City Centre": 19.2,
    "Mortgage As A Percentage Of Income": 58.71,
    "Affordability Index": 1.7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Sweden",
    "Price To Income Ratio": 9.27,
    "Gross Rental Yield City Centre": 3.08,
    "Gross Rental Yield Outside of Centre": 3.5,
    "Price To Rent Ratio City Centre": 32.45,
    "Price To Rent Ratio Outside Of City Centre": 28.54,
    "Mortgage As A Percentage Of Income": 61.57,
    "Affordability Index": 1.62,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iraq",
    "Price To Income Ratio": 9.12,
    "Gross Rental Yield City Centre": 5.9,
    "Gross Rental Yield Outside of Centre": 7.38,
    "Price To Rent Ratio City Centre": 16.94,
    "Price To Rent Ratio Outside Of City Centre": 13.55,
    "Mortgage As A Percentage Of Income": 99.66,
    "Affordability Index": 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Oman",
    "Price To Income Ratio": 9.08,
    "Gross Rental Yield City Centre": 3.56,
    "Gross Rental Yield Outside of Centre": 4.98,
    "Price To Rent Ratio City Centre": 28.07,
    "Price To Rent Ratio Outside Of City Centre": 20.09,
    "Mortgage As A Percentage Of Income": 71.33,
    "Affordability Index": 1.4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Estonia",
    "Price To Income Ratio": 9.06,
    "Gross Rental Yield City Centre": 4.02,
    "Gross Rental Yield Outside of Centre": 4.12,
    "Price To Rent Ratio City Centre": 24.9,
    "Price To Rent Ratio Outside Of City Centre": 24.26,
    "Mortgage As A Percentage Of Income": 57.2,
    "Affordability Index": 1.75,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Latvia",
    "Price To Income Ratio": 8.85,
    "Gross Rental Yield City Centre": 4.62,
    "Gross Rental Yield Outside of Centre": 5.3,
    "Price To Rent Ratio City Centre": 21.66,
    "Price To Rent Ratio Outside Of City Centre": 18.88,
    "Mortgage As A Percentage Of Income": 56.43,
    "Affordability Index": 1.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Norway",
    "Price To Income Ratio": 8.77,
    "Gross Rental Yield City Centre": 3.64,
    "Gross Rental Yield Outside of Centre": 4.09,
    "Price To Rent Ratio City Centre": 27.47,
    "Price To Rent Ratio Outside Of City Centre": 24.45,
    "Mortgage As A Percentage Of Income": 57.3,
    "Affordability Index": 1.75,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Switzerland",
    "Price To Income Ratio": 8.68,
    "Gross Rental Yield City Centre": 2.97,
    "Gross Rental Yield Outside of Centre": 3.28,
    "Price To Rent Ratio City Centre": 33.71,
    "Price To Rent Ratio Outside Of City Centre": 30.49,
    "Mortgage As A Percentage Of Income": 50.83,
    "Affordability Index": 1.97,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bahrain",
    "Price To Income Ratio": 8.63,
    "Gross Rental Yield City Centre": 7.46,
    "Gross Rental Yield Outside of Centre": 7.77,
    "Price To Rent Ratio City Centre": 13.41,
    "Price To Rent Ratio Outside Of City Centre": 12.88,
    "Mortgage As A Percentage Of Income": 77.22,
    "Affordability Index": 1.29,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "New Zealand",
    "Price To Income Ratio": 8.52,
    "Gross Rental Yield City Centre": 4.25,
    "Gross Rental Yield Outside of Centre": 4.58,
    "Price To Rent Ratio City Centre": 23.51,
    "Price To Rent Ratio Outside Of City Centre": 21.86,
    "Mortgage As A Percentage Of Income": 65.54,
    "Affordability Index": 1.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Bulgaria",
    "Price To Income Ratio": 8.52,
    "Gross Rental Yield City Centre": 5.23,
    "Gross Rental Yield Outside of Centre": 5.76,
    "Price To Rent Ratio City Centre": 19.14,
    "Price To Rent Ratio Outside Of City Centre": 17.36,
    "Mortgage As A Percentage Of Income": 61.27,
    "Affordability Index": 1.63,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Jordan",
    "Price To Income Ratio": 8.42,
    "Gross Rental Yield City Centre": 6.43,
    "Gross Rental Yield Outside of Centre": 7.09,
    "Price To Rent Ratio City Centre": 15.56,
    "Price To Rent Ratio Outside Of City Centre": 14.1,
    "Mortgage As A Percentage Of Income": 83.64,
    "Affordability Index": 1.2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Finland",
    "Price To Income Ratio": 8.35,
    "Gross Rental Yield City Centre": 3.3,
    "Gross Rental Yield Outside of Centre": 4.28,
    "Price To Rent Ratio City Centre": 30.34,
    "Price To Rent Ratio Outside Of City Centre": 23.37,
    "Mortgage As A Percentage Of Income": 48.1,
    "Affordability Index": 2.08,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Cyprus",
    "Price To Income Ratio": 8.2,
    "Gross Rental Yield City Centre": 6.17,
    "Gross Rental Yield Outside of Centre": 6.31,
    "Price To Rent Ratio City Centre": 16.2,
    "Price To Rent Ratio Outside Of City Centre": 15.85,
    "Mortgage As A Percentage Of Income": 55.94,
    "Affordability Index": 1.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Canada",
    "Price To Income Ratio": 7.97,
    "Gross Rental Yield City Centre": 4.29,
    "Gross Rental Yield Outside of Centre": 5.28,
    "Price To Rent Ratio City Centre": 23.33,
    "Price To Rent Ratio Outside Of City Centre": 18.94,
    "Mortgage As A Percentage Of Income": 56.41,
    "Affordability Index": 1.77,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Turkey",
    "Price To Income Ratio": 7.81,
    "Gross Rental Yield City Centre": 5.53,
    "Gross Rental Yield Outside of Centre": 5.95,
    "Price To Rent Ratio City Centre": 18.09,
    "Price To Rent Ratio Outside Of City Centre": 16.81,
    "Mortgage As A Percentage Of Income": 155.46,
    "Affordability Index": 0.64,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Australia",
    "Price To Income Ratio": 7.52,
    "Gross Rental Yield City Centre": 4.47,
    "Gross Rental Yield Outside of Centre": 4.67,
    "Price To Rent Ratio City Centre": 22.35,
    "Price To Rent Ratio Outside Of City Centre": 21.43,
    "Mortgage As A Percentage Of Income": 55.61,
    "Affordability Index": 1.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Netherlands",
    "Price To Income Ratio": 7.51,
    "Gross Rental Yield City Centre": 5.28,
    "Gross Rental Yield Outside of Centre": 5.56,
    "Price To Rent Ratio City Centre": 18.93,
    "Price To Rent Ratio Outside Of City Centre": 17.98,
    "Mortgage As A Percentage Of Income": 47.12,
    "Affordability Index": 2.12,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Ireland",
    "Price To Income Ratio": 7.49,
    "Gross Rental Yield City Centre": 6.64,
    "Gross Rental Yield Outside of Centre": 7.06,
    "Price To Rent Ratio City Centre": 15.05,
    "Price To Rent Ratio Outside Of City Centre": 14.17,
    "Mortgage As A Percentage Of Income": 52.5,
    "Affordability Index": 1.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Denmark",
    "Price To Income Ratio": 7.45,
    "Gross Rental Yield City Centre": 4.04,
    "Gross Rental Yield Outside of Centre": 4.07,
    "Price To Rent Ratio City Centre": 24.77,
    "Price To Rent Ratio Outside Of City Centre": 24.58,
    "Mortgage As A Percentage Of Income": 44.56,
    "Affordability Index": 2.24,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Belgium",
    "Price To Income Ratio": 6.91,
    "Gross Rental Yield City Centre": 4.92,
    "Gross Rental Yield Outside of Centre": 5.08,
    "Price To Rent Ratio City Centre": 20.33,
    "Price To Rent Ratio Outside Of City Centre": 19.67,
    "Mortgage As A Percentage Of Income": 41.27,
    "Affordability Index": 2.42,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Iceland",
    "Price To Income Ratio": 6.74,
    "Gross Rental Yield City Centre": 6.47,
    "Gross Rental Yield Outside of Centre": 7.16,
    "Price To Rent Ratio City Centre": 15.46,
    "Price To Rent Ratio Outside Of City Centre": 13.96,
    "Mortgage As A Percentage Of Income": 59.36,
    "Affordability Index": 1.68,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Trinidad And Tobago",
    "Price To Income Ratio": 6.1,
    "Gross Rental Yield City Centre": 11.36,
    "Gross Rental Yield Outside of Centre": 7.61,
    "Price To Rent Ratio City Centre": 8.8,
    "Price To Rent Ratio Outside Of City Centre": 13.15,
    "Mortgage As A Percentage Of Income": 54.47,
    "Affordability Index": 1.84,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Qatar",
    "Price To Income Ratio": 5.82,
    "Gross Rental Yield City Centre": 7.19,
    "Gross Rental Yield Outside of Centre": 7.38,
    "Price To Rent Ratio City Centre": 13.92,
    "Price To Rent Ratio Outside Of City Centre": 13.54,
    "Mortgage As A Percentage Of Income": 45.3,
    "Affordability Index": 2.21,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United Arab Emirates",
    "Price To Income Ratio": 5.29,
    "Gross Rental Yield City Centre": 9.05,
    "Gross Rental Yield Outside of Centre": 9.09,
    "Price To Rent Ratio City Centre": 11.05,
    "Price To Rent Ratio Outside Of City Centre": 11,
    "Mortgage As A Percentage Of Income": 39.23,
    "Affordability Index": 2.55,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Namibia",
    "Price To Income Ratio": 5.15,
    "Gross Rental Yield City Centre": 10.34,
    "Gross Rental Yield Outside of Centre": 10.3,
    "Price To Rent Ratio City Centre": 9.67,
    "Price To Rent Ratio Outside Of City Centre": 9.71,
    "Mortgage As A Percentage Of Income": 65.42,
    "Affordability Index": 1.53,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Palestine",
    "Price To Income Ratio": 4.38,
    "Gross Rental Yield City Centre": 7.16,
    "Gross Rental Yield Outside of Centre": 7.53,
    "Price To Rent Ratio City Centre": 13.97,
    "Price To Rent Ratio Outside Of City Centre": 13.28,
    "Mortgage As A Percentage Of Income": 46.46,
    "Affordability Index": 2.15,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "South Africa",
    "Price To Income Ratio": 3.93,
    "Gross Rental Yield City Centre": 9.85,
    "Gross Rental Yield Outside of Centre": 11.3,
    "Price To Rent Ratio City Centre": 10.15,
    "Price To Rent Ratio Outside Of City Centre": 8.85,
    "Mortgage As A Percentage Of Income": 47.5,
    "Affordability Index": 2.11,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Puerto Rico",
    "Price To Income Ratio": 3.53,
    "Gross Rental Yield City Centre": 9.34,
    "Gross Rental Yield Outside of Centre": 8.12,
    "Price To Rent Ratio City Centre": 10.7,
    "Price To Rent Ratio Outside Of City Centre": 12.31,
    "Mortgage As A Percentage Of Income": 27.25,
    "Affordability Index": 3.67,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "United States",
    "Price To Income Ratio": 3.52,
    "Gross Rental Yield City Centre": 10.36,
    "Gross Rental Yield Outside of Centre": 11.23,
    "Price To Rent Ratio City Centre": 9.65,
    "Price To Rent Ratio Outside Of City Centre": 8.9,
    "Mortgage As A Percentage Of Income": 26.35,
    "Affordability Index": 3.79,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    Country: "Saudi Arabia",
    "Price To Income Ratio": 2.79,
    "Gross Rental Yield City Centre": 7.22,
    "Gross Rental Yield Outside of Centre": 8.04,
    "Price To Rent Ratio City Centre": 13.84,
    "Price To Rent Ratio Outside Of City Centre": 12.43,
    "Mortgage As A Percentage Of Income": 20.64,
    "Affordability Index": 4.85,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
